// react/src/pages/PostForm.jsx
import { useEffect } from "react";
import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import router from "../router";
import { useStateContext } from "../ContextProvider";

export default function PostForm() {
  const [model, setModel] = useState([
    {
      id: "",
      title: "",
      body: "",
    },
  ]);

  const params = useParams();
  const { getSinglePost, savePost } = useStateContext();

  useEffect(() => {
    if (!params.id) {
      return;
    }

    setModel(getSinglePost(params.id));
  }, []);

  function onSubmit(ev) {
    ev.preventDefault();

    savePost(model);
    router.navigate("/");
  }

  return (
    <>
      <p>
        <Link to="/" className="btn btn-outline-secondary">
          Go back to post list
        </Link>
      </p>
      <div>
        <form onSubmit={onSubmit}>
          <h1>{model.id ? "Edit Post" : "Create new post"}</h1>
          <div className="mb-3">
            <input
              type="text"
              className="form-control"
              value={model.title}
              onInput={(ev) => setModel({ ...model, title: ev.target.value })}
              placeholder="Post Title"
            />
          </div>
          <div className="mb-3">
            <textarea
              type="text"
              className="form-control"
              value={model.body}
              onInput={(ev) => setModel({ ...model, body: ev.target.value })}
              placeholder="Post body"
            ></textarea>
          </div>
          <p>
            <button
              disabled={!model.title || !model.body}
              type="submit"
              className="btn btn-success"
            >
              Submit
            </button>
          </p>
        </form>
      </div>
    </>
  );
}

// vue/src/pages/PostForm.vue
<template>
    <div>
        <p>
            <RouterLink to="/" class="btn btn-outline-secondary">back to post list</RouterLink>
        </p>

        <form @submit.prevent="onSubmit">
            <h1>
                {{ model.id ? 'Edit Post' : 'Create new post' }}
            </h1>
            <div class="mb-3">
                <input
                    type="text"
                    class="form-control"
                    placeholder="Post Title"
                    v-model="model.title"
                />
            </div>
            <div class="mb-3">
                <textarea
                    type="text"
                    class="form-control"
                    placeholder="Post body"
                    v-model="model.body"
                ></textarea>
            </div>
            <p>
                <button
                    :disabled="!model.title || !model.body"
                    type="submit"
                    class="btn btn-success"
                >Submit</button>
            </p>
        </form>
    </div>
</template>

<script setup>
    import { ref, onMounted } from 'vue'
    import { useRoute, useRouter } from 'vue-router';
    import { useStore } from 'vuex'

    const route = useRoute()
    const router = useRouter()
    const store = useStore()

    const model = ref({
        id: '',
        title: '',
        body: ''
    })

    onMounted(async () => {
        if (!route.params.id) {
            return;
        }

        model.value = await store.dispatch('getSinglePost', route.params.id)
    })

    function onSubmit() {
        store.dispatch('savePost', model.value)
        .then(() => {
            router.push('/')
        })
    }
</script>

<style>

</style>
