// react/src/pages/PostList.jsx
import React from "react";
import { useState } from "react";
import { useEffect } from "react";
import { Link } from "react-router-dom";
import PostItem from "../components/PostItem";
import { useStateContext } from "../ContextProvider";

export default function PostList() {
  const { posts } = useStateContext();

  function onDelete(post) {
    setPostList(postList.filter((p) => p.id != post.id));
  }

  return (
    <>
      <p>
        <Link to="/new" className="btn btn-success">
          Add new
        </Link>
      </p>
      <div>
        {posts.map((post) => (
          <PostItem key={post.id} post={post} />
        ))}
      </div>
    </>
  );
}

// vue/src/pages/PostList.vue
<template>
    <div>
        <p>
            <RouterLink to="/new" class="btn btn-success">Add new</RouterLink>
        </p>
        <PostItem v-for="post of postList" :key="post.id" :post="post" />
    </div>
</template>

<script setup>
    import {computed, onMounted, ref} from 'vue'
    import PostItem from '../components/PostItem.vue'
    import {useStore} from 'vuex'

    const store = useStore()
    const postList = computed(() => store.state.posts)
</script>

<style>

</style>
